



public class ExceptionHandlingFour{
    public static void main (String ...args)
    {
        try {
            int a = 10 ; 
            int b = 0 ; 
            int c  = a/b;
        }
        // System.out.println("Hellow");// this will also shown an error  we cannot use any other statement inside the try and catch block
        //  catch (Exception e ) {
        //     e.printStackTrace();

        // }
        // catch(ArithmeticException e ) // we cannot use another catch block if we use the parent of exception class 

        // {
        //     e.printStackTrace();
        // }


        // catch (ArithmeticException e)
        // {
        //  e.printStackTrace();
        // }
        // catch (Exception e )
        // {
        //     e.printStackTrace();
        // }

        // finally{
        //     System.out.println("Finally terminalte");
        // }

  
        


        
    }
    
}
